/* eslint-disable */
// This file is auto-generated by scripts/generate-legal-content.mjs.
// Do not edit manually.

export type LegalSection = {
  heading: string;
  body: string[];
};

export type LegalDoc = {
  title: string;
  updated: string;
  sections: LegalSection[];
};

export const legalDocs = {
  "privacy": {
    "title": "Verity Privacy Policy (Draft)",
    "updated": "February 4, 2026",
    "sections": [
      {
        "heading": "Data We Collect",
        "body": [
          "Anonymous account ID",
          "Post-match profile details (name, photos, bio)",
          "Messages and token transactions",
          "Security logs (device, IP, user agent)",
          "We do not collect pre-match personal identifiers."
        ]
      },
      {
        "heading": "How We Use Data",
        "body": [
          "Provide matching, video sessions, and mutual reveal",
          "Prevent abuse and respond to safety reports",
          "Operate payments and fraud prevention"
        ]
      },
      {
        "heading": "Retention",
        "body": [
          "Non-match sessions are removed after 24 hours",
          "Matches are deleted on request via account deletion"
        ]
      },
      {
        "heading": "Third-Party Providers",
        "body": [
          "We rely on:",
          "Agora for video",
          "Hive for live moderation",
          "Stripe for payments"
        ]
      },
      {
        "heading": "Your Rights",
        "body": [
          "You can request access or deletion of your data at any time."
        ]
      },
      {
        "heading": "Contact",
        "body": []
      }
    ]
  },
  "terms": {
    "title": "Verity Terms of Service (Draft)",
    "updated": "February 4, 2026",
    "sections": [
      {
        "heading": "Eligibility",
        "body": [
          "You must be 18+ to use Verity."
        ]
      },
      {
        "heading": "Conduct",
        "body": [
          "No harassment, hate speech, or illegal activity",
          "No nudity or sexual content",
          "No recording of video sessions"
        ]
      },
      {
        "heading": "Tokens & Payments",
        "body": [
          "Tokens are non-refundable except where required by law. Tokens grant access to the queue and 45-second video sessions."
        ]
      },
      {
        "heading": "Disputes",
        "body": [
          "Governing law is Australia."
        ]
      },
      {
        "heading": "Contact",
        "body": []
      }
    ]
  },
  "community": {
    "title": "Verity Community Guidelines (Draft)",
    "updated": "February 4, 2026",
    "sections": [
      {
        "heading": "Respect & Safety",
        "body": [
          "Treat others with respect",
          "No harassment, threats, or hate speech",
          "No sharing of personal info without consent"
        ]
      },
      {
        "heading": "Moderation",
        "body": [
          "Reports are reviewed and may lead to warnings or bans",
          "Serious violations can result in immediate termination",
          "Appeals can be requested via support@verity.app"
        ]
      },
      {
        "heading": "Reporting",
        "body": [
          "Use the in-app report flow to flag misconduct."
        ]
      },
      {
        "heading": "Contact",
        "body": []
      }
    ]
  },
  "cookies": {
    "title": "Verity Cookie & Tracking Notice (Draft)",
    "updated": "February 4, 2026",
    "sections": [
      {
        "heading": "Essential Cookies",
        "body": [
          "We use cookies to keep you signed in and to protect your account."
        ]
      },
      {
        "heading": "Analytics",
        "body": [
          "We do not use advertising cookies in the beta."
        ]
      },
      {
        "heading": "Contact",
        "body": []
      }
    ]
  }
} as const satisfies Record<string, LegalDoc>;
